name: Cucumber CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build and run Docker image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t cucumber-example .
      - name: Run Docker image
        run: docker run -it --rm cucumber-example
